force-app/main/default/objects/Interrogation__c/Interrogation__c.object-meta.xml
<CustomObject>
    <label>Interrogation</label>
    <nameField>
        <displayFormat>Int-{0000}</displayFormat>
        <label>Interrogation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interrogations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interrogation__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interrogation__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Interrogation__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/Salesforce_Assist_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Salesforce Assist Question/Answer</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Salesforce Assist Question/Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Assist Question/Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Account_Business_Process__c</fullName>
    <label>Account Business Process</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_1__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_1__c</fullName>
    <inlineHelpText>Are Accounts used in other custom object?</inlineHelpText>
    <label>Account Q.1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_2__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_2__c</fullName>
    <inlineHelpText>How many record types are there in this object?</inlineHelpText>
    <label>Account Q.2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_3__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_3__c</fullName>
    <inlineHelpText>How many page layouts are there in this object?</inlineHelpText>
    <label>Account Q.3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_4__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_4__c</fullName>
    <inlineHelpText>How many duplicate rules are there in this object?</inlineHelpText>
    <label>Account Q.4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_5__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_5__c</fullName>
    <inlineHelpText>What are the triggers which are triggered by relate to the Account object?</inlineHelpText>
    <label>Account Q.5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_6__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_6__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The Person account is enabled?</inlineHelpText>
    <label>Account Q.6</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Account_Q_7__c.field-meta.xml
<CustomField>
    <fullName>Account_Q_7__c</fullName>
    <inlineHelpText>Any Validations implemented?</inlineHelpText>
    <label>Account Q.7</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Contact_Business_Process__c</fullName>
    <label>Contact Business Process</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_1__c</fullName>
    <inlineHelpText>Are Contact used in other custom object?</inlineHelpText>
    <label>Contact Q.1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_2__c</fullName>
    <inlineHelpText>How many record types are there in this object?</inlineHelpText>
    <label>Contact Q.2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_3__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_3__c</fullName>
    <inlineHelpText>How many page layouts are there in this object?</inlineHelpText>
    <label>Contact Q.3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_4__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_4__c</fullName>
    <inlineHelpText>How many duplicate rules are there in this object?</inlineHelpText>
    <label>Contact Q.4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_5__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_5__c</fullName>
    <inlineHelpText>What are the triggers which are triggered by relate to the Contact object?</inlineHelpText>
    <label>Contact Q.5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_6__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_6__c</fullName>
    <inlineHelpText>Are you having any Validations on Contact?</inlineHelpText>
    <label>Contact Q.6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Contact_Q_7__c.field-meta.xml
<CustomField>
    <fullName>Contact_Q_7__c</fullName>
    <inlineHelpText>If activities are being used anywhere in the Contacts object.</inlineHelpText>
    <label>Contact Q.7</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Lead_Business_Process__c</fullName>
    <description>This field used to contains business process data.</description>
    <label>Lead Business Process</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_1__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_1__c</fullName>
    <inlineHelpText>If activities are being used anywhere in the LEADS object.</inlineHelpText>
    <label>Lead Q.1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_2__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_2__c</fullName>
    <inlineHelpText>How the leads progress through the status.</inlineHelpText>
    <label>Lead Q.2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_3__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_3__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Are leads being converted?</inlineHelpText>
    <label>Lead Q.3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_4__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_4__c</fullName>
    <inlineHelpText>What is the source of the leads (3rd party tools, web to Lead, manual input)?</inlineHelpText>
    <label>Lead Q.4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_5__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_5__c</fullName>
    <inlineHelpText>Are Leads used in other custom object?</inlineHelpText>
    <label>Lead Q.5</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_6__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_6__c</fullName>
    <inlineHelpText>How many record types are there in this object?</inlineHelpText>
    <label>Lead Q.6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_7__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_7__c</fullName>
    <inlineHelpText>How do you manage and track duplicate leads?</inlineHelpText>
    <label>Lead Q.7</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_8__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_8__c</fullName>
    <inlineHelpText>Is there Workflow or any other Automations used?</inlineHelpText>
    <label>Lead Q.8</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Lead_Q_9__c.field-meta.xml
<CustomField>
    <fullName>Lead_Q_9__c</fullName>
    <inlineHelpText>What are the validation rule?</inlineHelpText>
    <label>Lead Q.9</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Business_Process__c</fullName>
    <label>Opportunity Business Process</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_1__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_1__c</fullName>
    <inlineHelpText>Are products being related to the opportunity object (Give a percentage of opportunities which have products related to it)?</inlineHelpText>
    <label>Opportunity Q.1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_2__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_2__c</fullName>
    <inlineHelpText>If activities are being used anywhere in the Opportunity object.</inlineHelpText>
    <label>Opportunity Q.2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_3__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_3__c</fullName>
    <inlineHelpText>What is the path for the opportunity object?</inlineHelpText>
    <label>Opportunity Q.3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_4__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_4__c</fullName>
    <inlineHelpText>Are Opportunity used in other custom object?</inlineHelpText>
    <label>Opportunity Q.4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_5__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_5__c</fullName>
    <inlineHelpText>How many record types are there in this object?</inlineHelpText>
    <label>Opportunity Q.5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_6__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_6__c</fullName>
    <inlineHelpText>What are the flows and triggers which are triggered by relate to the opportunity object?</inlineHelpText>
    <label>Opportunity Q.6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_7__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_7__c</fullName>
    <inlineHelpText>What are the validation rule?</inlineHelpText>
    <label>Opportunity Q.7</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_8__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_8__c</fullName>
    <inlineHelpText>How do you manage Duplicate Opportunity?</inlineHelpText>
    <label>Opportunity Q.8</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Assist_Question_Answer__c/fields/Opportunity_Q_9__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Q_9__c</fullName>
    <inlineHelpText>How many page layouts are there in this object?</inlineHelpText>
    <label>Opportunity Q.9</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/*
Created By          : Girikon (Mohd Sahil)
Created On          : July 03, 2024
@description        : 

Modification log --
Modified By         : 
Modified On         : 
*/
@isTest
public with sharing class TestDataFactory {
    
    // This method insert record into Salesforce assist questions answer.
    public static Salesforce_Assist_Question_Answer__c assistDataAssistQuestionAnswerInsert()
    {
        Salesforce_Assist_Question_Answer__c assistData = new Salesforce_Assist_Question_Answer__c();
        assistData.Lead_Q_1__c = 1.1;
        assistData.Lead_Q_2__c = 'Answer 2';
        assistData.Lead_Q_3__c = true;
        assistData.Lead_Q_4__c = 'Answer 4';
        assistData.Lead_Q_5__c = 'Answer 5';
        assistData.Lead_Q_6__c = 1;
        assistData.Lead_Q_7__c = 2.1;
        assistData.Lead_Q_8__c = 2.2;
        assistData.Lead_Q_9__c = 2.3;
        assistData.Lead_Business_Process__c = 'Diagram';
        assistData.Account_Q_1__c = 'Test';
        assistData.Account_Q_2__c = 2;
        assistData.Account_Q_3__c = 6;
        assistData.Account_Q_4__c = 1;
        assistData.Account_Q_5__c = 3;
        assistData.Account_Q_6__c = false;
        assistData.Account_Q_7__c = 1;
        assistData.Account_Business_Process__c = 'Diagram2';
        assistData.Contact_Q_1__c = 'Test1';
        assistData.Contact_Q_2__c = 1;
        assistData.Contact_Q_3__c = 1.2;
        assistData.Contact_Q_4__c = 8;
        assistData.Contact_Q_5__c = 4;
        assistData.Contact_Q_6__c = 6;
        assistData.Contact_Q_7__c = 7;
        assistData.Contact_Business_Process__c = 'Diagram3';
        assistData.Opportunity_Q_1__c = 2.1;
        assistData.Opportunity_Q_2__c = 2.2;
        assistData.Opportunity_Q_3__c = 'test3';
        assistData.Opportunity_Q_4__c = 'test4';
        assistData.Opportunity_Q_5__c = 1;
        assistData.Opportunity_Q_6__c = 2;
        assistData.Opportunity_Q_7__c = 4;
        assistData.Opportunity_Q_8__c = 2;
        assistData.Opportunity_Q_9__c = 1;
        assistData.Opportunity_Business_Process__c = 'Diagram4';

        insert assistData;

        return assistData;
    }
     // This method used to return Account instance.
     public static Account createAccountInstance()
     {
         Account acc=new Account(
             Name = 'Sahil',
             Phone = '1234567890'
         );
 
         return acc;
     }

    // This method used to return contact instance.
    public static Contact createContactInstance()
    {
        Contact cont=new Contact(
            LastName = 'Sahil'
        );

        return cont;
    }

    // This method used to return task instance.
    public static Task createTaskInstance()
    {
        Task tsk = new Task(Subject = 'Test Task');

        return tsk;
    }

    public static Interrogation__c createInterrogationIntance()
    {
         Interrogation__c interrogate = new Interrogation__c(
            Label__c = 'Name',
            Object_Type__c = 'Lead',
            DataType__c	= 'Text',
            Pick_Values__c = 'test1;test2'
         );
         return interrogate;
    }

    public static Salesforce_Assist_Score__c createSalesforceAssistScoreRecord()
    {
        Salesforce_Assist_Score__c assistScore = new Salesforce_Assist_Score__c(
            Scoring_Rule_Name__c = 'Number should not be blank.',
            Object_Type__c = 'Lead',
            Output__c	= 10,
            Rule__c = 'Number should not be blank.'
         );
         return assistScore;
    }

}