force-app/main/default/objects/PRM_SRM_Setting__mdt/PRM_SRM_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains the mapping to assign PRM &amp; SRM to Contact records.</description>
    <label>PRM &amp; SRM Setting</label>
    <pluralLabel>PRM &amp; SRM Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PRM_SRM_Setting__mdt/fields/Opportunity_Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type_Name__c</fullName>
    <description>Enter the Record Type Name (DeveloperName) of Opportunity.</description>
    <inlineHelpText>Enter the Record Type Name (DeveloperName) of Opportunity.</inlineHelpText>
    <label>Opportunity Record Type Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRM_SRM_Setting__mdt/fields/PRM_Username__c.field-meta.xml
<CustomField>
    <fullName>PRM_Username__c</fullName>
    <description>Enter the username of user who is going to be PRM.</description>
    <inlineHelpText>Enter the username of user who is going to be PRM.</inlineHelpText>
    <label>PRM Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRM_SRM_Setting__mdt/fields/SRM_Username__c.field-meta.xml
<CustomField>
    <fullName>SRM_Username__c</fullName>
    <description>Enter the username of user who is going to be SRM.</description>
    <inlineHelpText>Enter the username of user who is going to be SRM.</inlineHelpText>
    <label>SRM Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRM_SRM_Setting__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Enter the State and if not available then enter &apos;Blank&apos;.</description>
    <inlineHelpText>Enter the State and if not available then enter &apos;Blank&apos;.</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PRMSRMDataUpdateBatch.cls
/* 
* Created By:   {Girikon(Sahil Khan)}
* Created On:   Sep 02, 2024
* Description/Purpose:  Batch class to update PRM and SRM fields for xeisting Contacts.
* Test Class:   {PRMSRMDataUpdateBatch_Test} {Coverage __% }
*
* Modification log --
*/
public with sharing class PRMSRMDataUpdateBatch implements Database.Batchable<sObject>
{
    public Database.QueryLocator start(Database.BatchableContext bc) 
    {
        return Database.getQueryLocator(
            'SELECT Id, Primary_Relationship_Manager__c, Secondary_Relationship_Manager__c, MailingState FROM Contact'
        );
    }
    public void execute(Database.BatchableContext bc, List<Contact> records)
    {
        Boolean isGrant = false;
        Boolean isCorporateOrInKind = false;
        Boolean isDonation = false;
        Boolean isOther = false;
        List<Opportunity> oppList = [SELECT Id, RecordType.DeveloperName FROM Opportunity WHERE npsp__Primary_Contact__c = :records[0].Id AND IsWon = true AND Amount > 0];
        if(!oppList.isEmpty())
        {
            for(Opportunity opp : oppList)
            {
                if(opp.RecordType.DeveloperName == 'Grant') 
                {
                    isGrant = true;
                }
                else if(opp.RecordType.DeveloperName == 'Corporate' || opp.RecordType.DeveloperName == 'InKindGift')
                {
                    isCorporateOrInKind = true;
                }
                else if(opp.RecordType.DeveloperName == 'Donation') 
                {
                    isDonation = true;
                }
                else if(opp.RecordType.DeveloperName == 'MatchingGift' || opp.RecordType.DeveloperName == 'MajorGift' || opp.RecordType.DeveloperName == 'Bequest' || opp.RecordType.DeveloperName == 'Membership')
                {
                    isOther = true;
                }
            }
            PRM_SRM_Setting__mdt mdt = new PRM_SRM_Setting__mdt();
            if(isGrant)
            {
                mdt = PRMSRMDataUpdateBatch.getPRM_SRMSettings('Grant', 'Blank');
            }
            else if(isCorporateOrInKind)
            {
                mdt = PRMSRMDataUpdateBatch.getPRM_SRMSettings('Corporate', 'Blank');
            }
            else if(isDonation)
            {
                mdt = PRMSRMDataUpdateBatch.getPRM_SRMSettings('Donation', records[0].MailingState);
            }
            else if(isOther)
            {
                mdt = PRMSRMDataUpdateBatch.getPRM_SRMSettings('MajorGift', 'Blank');
            }
            List<User> userList = [SELECT Id, Username FROM User WHERE Username = :mdt.PRM_Username__c OR Username = :mdt.SRM_Username__c];
            for(User usr : userList)
            {
                if(usr.Username == mdt.PRM_Username__c)
                {
                    records[0].Primary_Relationship_Manager__c = usr.Id;
                }
                if(usr.Username == mdt.SRM_Username__c)
                {
                    records[0].Secondary_Relationship_Manager__c = usr.Id;
                }
            }
            UPDATE records[0];
        }
    }
    public void finish(Database.BatchableContext bc)
    {
        // execute any post-processing operations
    }
    public static PRM_SRM_Setting__mdt getPRM_SRMSettings(String recordTypeName, String state)
    {
        List<PRM_SRM_Setting__mdt> mdtList = [SELECT Id, Opportunity_Record_Type_Name__c, PRM_Username__c, SRM_Username__c, State__c FROM PRM_SRM_Setting__mdt WHERE Opportunity_Record_Type_Name__c = :recordTypeName AND State__c = :state];
        if(mdtList.isEmpty())
        {
            mdtList = [SELECT Id, Opportunity_Record_Type_Name__c, PRM_Username__c, SRM_Username__c, State__c FROM PRM_SRM_Setting__mdt WHERE Opportunity_Record_Type_Name__c = :recordTypeName AND State__c = 'Blank'];
        }
        return mdtList[0];
    }
}